import { z } from 'zod';

const port = z.number().int().min(1).max(65535);
const nonNegativeInt = z.number().int().min(0);
const absolutePath = z.string().regex(/^\//, 'pages.settings.validation.pathLeadingSlash');

export const AllSettingSchema = z.object({
  webListen: z.string().optional(),
  webDomain: z.string().optional(),
  webPort: port.optional(),
  webCertFile: z.string().optional(),
  webKeyFile: z.string().optional(),
  webBasePath: absolutePath.optional(),
  sessionMaxAge: z.number().int().min(1).max(525600).optional(),
  trustedProxyCIDRs: z.string().optional(),
  panelOutbound: z.string().optional(),
  pageSize: z.number().int().min(0).max(1000).optional(),
  expireDiff: nonNegativeInt.optional(),
  trafficDiff: nonNegativeInt.max(100).optional(),
  remarkTemplate: z.string().optional(),
  datepicker: z.enum(['gregorian', 'jalalian']).optional(),
  tgLang: z.string().optional(),
  twoFactorEnable: z.boolean().optional(),
  twoFactorToken: z.string().optional(),
  xrayTemplateConfig: z.string().optional(),
  subEnable: z.boolean().optional(),
  subJsonEnable: z.boolean().optional(),
  subTitle: z.string().optional(),
  subSupportUrl: z.string().optional(),
  subProfileUrl: z.string().optional(),
  subAnnounce: z.string().optional(),
  subEnableRouting: z.boolean().optional(),
  subRoutingRules: z.string().optional(),
  subIncyEnableRouting: z.boolean().optional(),
  subIncyRoutingRules: z.string().optional(),
  subPath: absolutePath.optional(),
  subJsonPath: absolutePath.optional(),
  subClashEnable: z.boolean().optional(),
  subClashPath: absolutePath.optional(),
  externalTrafficInformEnable: z.boolean().optional(),
  externalTrafficInformURI: z.string().optional(),
  restartXrayOnClientDisable: z.boolean().optional(),
  subUpdates: z.number().int().min(1).max(168).optional(),
  subEncrypt: z.boolean().optional(),
  subURI: z.string().optional(),
  subJsonURI: z.string().optional(),
  subClashURI: z.string().optional(),
  subClashEnableRouting: z.boolean().optional(),
  subClashRules: z.string().optional(),
  subJsonMux: z.string().optional(),
  subJsonRules: z.string().optional(),
  subJsonFinalMask: z.string().optional(),
  subHideSettings: z.boolean().optional(),
  timeLocation: z.string().optional(),
  hasTwoFactorToken: z.boolean().optional(),
  hasApiToken: z.boolean().optional(),
  hasWarpSecret: z.boolean().optional(),
  hasNordSecret: z.boolean().optional(),
  hasSmtpPassword: z.boolean().optional(),
}).loose();

export type AllSettingInput = z.infer<typeof AllSettingSchema>;
